pipeline {
  agent any
  
  stages {
    stage('Créer le compte utilisateur') {
      steps {
        script {
          // Définir les informations utilisateur
          def username = "Test"
          def password = "Pa$$w0rd"
          
          // Créer l'utilisateur dans OES
          sh "oesadmin -a ${username} -p ${password} -t user"
          sh "oesadmin -a ${username} -g default"
          
          // Créer l'utilisateur dans Office 365
          sh "New-MsolUser -UserPrincipalName ${username}@test.com -DisplayName 'Test' -FirstName John -LastName Doe -Password ${password}"
          sh "Set-MsolUser -UserPrincipalName ${username}@test.com -UsageLocation US"
          
          // Créer l'utilisateur dans Oasis
          sh "oasis adduser ${username} -p ${password} -g default"
        }
      }
    }
  }
}
